-- MySQL Script generated by MySQL Workbench
-- Wed Jul 12 23:08:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agencyth_liveprod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agencyth_liveprod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencyth_liveprod` DEFAULT CHARACTER SET utf8 ;
USE `agencyth_liveprod` ;

-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_customer` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primary_firstname` VARCHAR(45) NULL,
  `primary_lastname` VARCHAR(45) NULL,
  `primary_telno` VARCHAR(75) NULL,
  `primary_cellphone` VARCHAR(75) NULL,
  `primary_alt_telno` VARCHAR(75) NULL,
  `primary_address` VARCHAR(255) NULL,
  `primary_email` VARCHAR(75) NULL,
  `primary_emergency_contact` VARCHAR(45) NULL,
  `secondary_firstname` VARCHAR(45) NULL,
  `secondary_lastname` VARCHAR(45) NULL,
  `secondary_telno` VARCHAR(75) NULL,
  `secondary_cellphone` VARCHAR(75) NULL,
  `secondary_alt_telno` VARCHAR(75) NULL,
  `secondary_address` VARCHAR(255) NULL,
  `secondary_email` VARCHAR(75) NULL,
  `secondary_emergency_contact` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_colour_scheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_colour_scheme` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_colour_scheme` (
  `id` INT NOT NULL,
  `scheme_name` VARCHAR(45) NULL,
  `color_1` VARCHAR(45) NULL,
  `color_2` VARCHAR(45) NULL,
  `color_3` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_account_setup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_account_setup` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_account_setup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(75) NULL,
  `agency_name` VARCHAR(75) NULL,
  `logo` TEXT NULL,
  `password` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `smtp_server` VARCHAR(255) NULL,
  `smtp_username` VARCHAR(45) NULL,
  `smtp_password` VARCHAR(255) NULL,
  `apointment_locations` TEXT NULL,
  `staff` TEXT NULL,
  `colour_scheme_id` INT NOT NULL,
  `is_auto_checked` TINYINT NULL DEFAULT 1 COMMENT 'Check: tbl_policy_type',
  `is_home_checked` TINYINT NULL DEFAULT 1 COMMENT 'Check: tbl_policy_type',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_ci_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_ci_review` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_ci_review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assessment_guid` VARCHAR(255) NULL,
  `customer_id` INT NULL,
  `ci_review_submitted_to` VARCHAR(255) NULL COMMENT 'Email address of NA receipient',
  `ci_review_guid` VARCHAR(255) NULL,
  `is_steps_completed` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_action_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_action_item` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_action_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL COMMENT 'FK: tbl_customer',
  `action_type_code` VARCHAR(45) NULL COMMENT 'FK: tbl_action_type',
  `owner` VARCHAR(45) NULL COMMENT 'This is based on the selected staff (Account Setup)',
  `description` TEXT NULL,
  `ci_review_guid` VARCHAR(255) NULL COMMENT 'FK: tbl_ci_review',
  `is_opportunity` TINYINT NULL,
  `is_completed` TINYINT NULL DEFAULT 0 COMMENT ' Insurance Agent will mark this Action Item if completed',
  `created_date` TIMESTAMP NULL,
  `due_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_current_coverage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_current_coverage` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_current_coverage` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `policy_parent_code` VARCHAR(45) NULL COMMENT 'Values are: \"Auto\" or \"Home\"',
  `policy_child_label` VARCHAR(45) NULL,
  `policy_child_selected` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_feedback` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `page_url` TEXT NOT NULL COMMENT 'URL they have concern about',
  `reporter_name` VARCHAR(45) NOT NULL COMMENT 'Required',
  `reporter_email` VARCHAR(255) NULL COMMENT 'Optional',
  `message` TEXT NOT NULL COMMENT 'Feedback message by the users',
  `status` VARCHAR(45) NOT NULL DEFAULT 'Open' COMMENT 'Status of the reported feedback',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_account_setup_policy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_account_setup_policy` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_account_setup_policy` (
  `id` INT NOT NULL,
  `policy_parent_label` ENUM('Auto', 'Home') NULL COMMENT 'Values are: \"Home\" and \"Auto\"',
  `policy_child_label` VARCHAR(45) NULL,
  `policy_child_questions` TEXT NULL,
  `policy_child_values` MEDIUMTEXT NULL,
  `is_child_checked` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `IX_policy_parent` (`policy_parent_label` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_note` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `page_index_url` VARCHAR(45) NULL,
  `msg_note` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_action_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_action_type` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_action_type` (
  `action_type_code` VARCHAR(45) NOT NULL COMMENT 'Values: Customer Contact, Dependents, Auto, Home, Concerns and Questions',
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`action_type_code`),
  UNIQUE INDEX `action_type_code_UNIQUE` (`action_type_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_dependent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_dependent` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_dependent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `dependent_name` VARCHAR(45) NULL,
  `dependent_age` VARCHAR(45) NULL COMMENT 'Ages is in the range of 0-100  (this includes Baby, Kids, Adults)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_needs_assessment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_needs_assessment` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_needs_assessment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assessment_guid` VARCHAR(255) NULL,
  `customer_id` INT NULL,
  `assessment_submitted_to` VARCHAR(255) NULL COMMENT 'Email address of NA receipient',
  `is_steps_completed` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_appointment` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_appointment` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `appointment_date` DATE NULL,
  `appointment_time` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL COMMENT 'Check: tbl_account_setup',
  `is_steps_completed` TINYINT NULL COMMENT 'Flag if steps are now completed',
  `assessment_guid` VARCHAR(255) NULL COMMENT 'Relate: Need Assessment',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_activity_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_activity_meta` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_activity_meta` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `meta_key` VARCHAR(255) NULL COMMENT 'This store comma delimited data, to use for referencing on a Transaction',
  `meta_value` TEXT NULL COMMENT 'This store json data, or plain data',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_policy_line_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_policy_line_question` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_policy_line_question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `assessment_guid` VARCHAR(255) NULL,
  `policy_parent_label` VARCHAR(45) NULL,
  `policy_child_label` VARCHAR(45) NULL,
  `policy_child_selected` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_policies_in_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_policies_in_place` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_policies_in_place` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `assessment_guid` VARCHAR(255) NULL,
  `policy_parent_label` VARCHAR(45) NULL,
  `policy_child_label` VARCHAR(45) NULL,
  `insurance_company` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_top_concerns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_top_concerns` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_top_concerns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `assessment_guid` VARCHAR(255) NULL,
  `concern_question` VARCHAR(45) NULL,
  `concern_answer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_life_changes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_life_changes` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_life_changes` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `assessment_guid` VARCHAR(255) NULL,
  `life_question` VARCHAR(45) NULL,
  `life_answer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_long_term_goals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_long_term_goals` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_long_term_goals` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `assessment_guid` VARCHAR(255) NULL,
  `goal_question` VARCHAR(45) NULL,
  `goal_answer` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_goals_concern`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_goals_concern` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_goals_concern` (
  `id` INT NOT NULL,
  `customer_id` INT NULL,
  `ci_review_guid` VARCHAR(255) NULL,
  `action_type` VARCHAR(45) NULL COMMENT 'This only save \"Goal\" and \"Concern\"',
  `action_description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencyth_liveprod`.`tbl_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencyth_liveprod`.`tbl_education` ;

CREATE TABLE IF NOT EXISTS `agencyth_liveprod`.`tbl_education` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `policy_parent_label` VARCHAR(45) NULL,
  `policy_child_label` VARCHAR(45) NULL,
  `policy_child_selected` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
